<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dev.eposs.pcf</groupId>
    <artifactId>PhoenixCommandFramework</artifactId>
    <version>0.4.2</version>
    
    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.dv8tion</groupId>
            <artifactId>JDA</artifactId>
            <version>[6.0.0,7.0.0)</version>
        </dependency>
    </dependencies>
    
    <name>PhoenixCommandFramework</name>
    <description>Command Utility for JDA</description>
    <url>https://github.com/Eposs10/PhoenixCommandFramework</url>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://license.eposs.dev/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>Eposs</id>
            <name>Eposs</name>
            <email>mail@eposs.dev</email>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/Eposs10/PhoenixCommandFramework</connection>
        <developerConnection>scm:git:ssh://github.com:Eposs10/PhoenixCommandFramework.git</developerConnection>
        <url>https://github.com/Eposs10/PhoenixCommandFramework</url>
    </scm>
</project>