name: Publish to Maven Central

on:
  workflow_dispatch:

concurrency:
  group: "publish"

jobs:
  publish:
    environment: maven-central-release
    runs-on: ubuntu-latest

    permissions:
      contents: write  # needed to create releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java and Maven Central credentials
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Build and publish
        run: mvn --batch-mode --no-transfer-progress clean deploy
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Get version from POM
        id: get_version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: target/*.jar
          generate_release_notes: true
