name: Publish to Maven Central

on:
  workflow_dispatch:

concurrency:
  group: "publish"

jobs:
  publish:
    environment: maven-central-release
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java and Maven Central credentials
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Build and publish
        run: mvn --batch-mode --no-transfer-progress clean deploy
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: target/*.jar